{/*jslint node: true */
"use strict";

// Seed math

exports.random = x => {
    return x * Math.random();
};

exports.randomAngle = () => {
    return Math.PI * 2 * Math.random();
};

exports.randomRange = (min, max) => {
    return Math.random() * (max - min) + min;
};

exports.irandom = i => {
    let max = Math.floor(i);
    return Math.floor(Math.random() * (max + 1)); //Inclusive
};

exports.irandomRange = (min, max) => {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min; //Inclusive
};

exports.gauss = (mean, deviation) => {
    let x1, x2, w;
    do {
        x1 = 2*Math.random() - 1;
        x2 = 2*Math.random() - 1;
        w = x1 * x1 + x2 * x2;
    } while (0 == w || w >= 1);

    w = Math.sqrt(-2 * Math.log(w) / w);
    return mean + deviation * x1 * w;
};

exports.gaussInverse = (min, max, clustering) => {
    let range = max - min;
    let output = exports.gauss(0, range / clustering);

    while (output < 0) {
        output += range;
    }
    
    while (output > range) {
        output -= range;
    }
    
    return output + min;
};

exports.gaussRing = (radius, clustering) => {
    let r = exports.random(Math.PI * 2);
    let d = exports.gauss(radius, radius*clustering);
    return {
        x: d * Math.cos(r),
        y: d * Math.sin(r),
    };
};

exports.chance = prob => {
    return exports.random(1) < prob;
};

exports.dice = sides => {
    return exports.random(sides) < 1;
};

exports.choose = arr => {
    return arr[exports.irandom(arr.length - 1)];
};

exports.chooseN = (arr, n) => {
    let o = [];
    for (let i=0; i<n; i++) {
        o.push(arr.splice(exports.irandom(arr.length - 1), 1)[0]);
    }
    return o;
};

exports.chooseChance = (...arg) => {
    let totalProb = 0;
    arg.forEach(function(value) { totalProb += value; });
    let answer = exports.random(totalProb);
    for (let i=0; i<arg.length; i++) {
        if (answer<arg[i]) return i;
        answer -= arg[i];
    }
};


exports.chooseBotName = () => {
    /*return exports.choose([
        'Alpha',
        'boss',
        'November',
        'Victor',
        'X-Ray',
        'ñ',
        'im not a bot',
        'premium',
        '#Shorts',
        'новобранец',
        '11000011 10110001',
        'ü',
        'XD',
        'IP: 425.257.587',
        '',
        'ZzZ',
        'XD 2',
        'fuck you',
        'humans = trash',
        'UWU',
        '3rR0R',
        'dead furrys',
        'que pro',
        '([{¿¡a!?}])',
        'Laaaaaaag',
        '100% bot',
        'michi',
        'tank',
        'el Xokas',
        'que pro en 4k',
        'A',
        'fdhgfhjk',
        'MISSIGNO',
        'Minecraft',
        'free fire is good',
        'free fire is ZzZ',
        'Geometry dash',
        'Undefined',
        'an unnamed tank',
        'hexagon',
        'la roca XD',
        'Ñ + Ç =???',
        'do not kill me',
        'XP',
        'Que pendej*',
        '360 / 7 = 51.4285714286',
        'ehjeihjiehjhiehjheihej',
        'you',
        'Im bot',
        'spelling error',
        'MEXICANO',
        'á, é, í, ó, ú',
        'Bob',
        'Carmen',
        'David',
        'Janet',
        'Lorenzo',,
        'Roger',
        'Tommy 11',
        'Vincent',
        'Delta',
        'Lima',
        'November',
        'Uniform',
        'Zulu',
        'undefined',
        'VIVA LATAM',
        'paladise',
        'battleship',
        'Anhihilator',
        'Nailgun',
        'Mach gun',
        'NACHOS',
        'your ZzZ',
        'CSM',
        'Peru',
        'Argentina',
        'United States',
        'ahhhhh',
        'other name more',
        'Canada',
        'USA',
        'No deberia existir XD',
        //'porque soy este equpo :(',
        '???',
        ':)',
        'Alejandro',
        'head',
        'beta tester',
        'good day',
        'bye',
        'LOVE = ilusion',
        'Happy new year',
        'Merry christmas',
        'dulce o mierda',
        'oh estoy bloqueado',
        ////(let * = 4;);
        '4Ml0 é G*Y',
        //'im Alklina',
        'let ñ = n+-',
        'glitch is ZzZ',
        'glitch is good',
        'the R',
        'earth',
        //'ladron',
        'palta',
        'aguacate',
        'MAS Ñ',
        //'bailar',
        ',.;:+-/*[´{()}´]',
        '´´',
        //'+',
        //'-',
        //'AWA',
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        'day 1',
        'New Assault',
        'im stupid',
        'ho',
        ' ',
        //'happy 4 july',
        'Jaunary',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'December',
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Monday',
        'Lunes',
        'Peggle',
        '2023 sorprendeme',
        'MAGIC! Rude',
        'Poker Face',
        'Aserejé',
        'Material Girl',
        'Notch',
        'David Medrano',
        'Pumped Up Kicks',
        'PC',
        'Computer',
        'AI_',
        'á é í ó ú ü ç',
        'Andre100proo XD',
        'Andre100pro XD',
        'Andre100',
        'Funado!',
        '123456789',
        'Foster the Pepole',
        'Wenomechainsama',
        'Tumajarbisaun',
        'Wifenlooof',
        'Eselifterbraun',
        'Arena Closer',
        'Sin Importar',
        'hi',
        'Tank',
        'Basic Tank Guy',
        'Feash',
        'Max XD',
        'ALIMENTAME',
        'SNIPPER',
        'I´m a cute girl',
        'm',
        'Moves Like Jagger',
        'New Rules',
        'Overmancer YT',
        'Praca',
        'Jymmi',
        'Jimmy',
        ':D',
        '342',
        'Strong',
        'Woomy arras.io',
        'The woorm house',
        '3!',
        '2!',
        '1!',
        '250 Names!',
        'Marckito',
        'ryuu',
        'hadlof itler',
        '',
        '',
        '',
        '',
        'temertly',
        'this is tale of',
        'Hate___love++++',
        '_',
        '-',
        '|',
        '[base]',
        '[fire]',
        '[water]',
        'Adolf[base]',
        'Hitler[fire]',
        'Naz1[water]',
        'germany[trap]',
        'odin[octo]',
        '[octo]',
        '[VN]infinity',
        'H.js',
        '[KPK]',
        '[KPK]penetrator',
        '[VN]',
        'Bean OStm',
        '[sword]...',
        '²■☺',
        '☺☻♥♦♣♠•◘○',
        '◘◘◘◘◘◘',
        'WHITE.404',
        '3 week no play',
        '[VPN]',
        '[VPN]69 89',
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'n',
        'o',
        'p',
        'q',
        'r',
        's',
        't',
        'u',
        'v',
        'w',
        'x',
        'y',
        'z',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'KILLER 💀',
        'skibidi toilet',
        'Thiepkiel',
        'Nytrxi',
        'pet',
        'inifensive',
        '👽 Alien 👽',
        'XxX pedrito XxX',
        'π',
        'π = 3,14159265358979323846264338327950288419716939',
        'Ukranie',
        'Ukranie peace',
        'titan camera',
        'titan speakerman',
        'titan Tv',
        'cameraman',
        'speakerman',
        'Tv-man',//{
        'Alpha',
        'boss',
        'November',
        'Victor',
        'X-Ray',
        'ñ',
        'im not a bot',
        'premium',
        'новобранец',
        '11000011 10110001',
        'pink cheese green goes',
        'VIVA MÉXICO',
        'ü',
        'XD',
        'IP: 425.257.587',
        '',
        'que noob',
        'andre100noob DX',
        'ZzZ',
        'fuck you',
        '3rR0R',
        '([{¿¡a!?}])',
        'Laaaaaaag',
        '100% bot',
        'michi',
        'tank',
        'A',
        'fdhgfhjk',
        'Undefined',
        'an unnamed tank',
        'hexagon',
        'Ñ + Ç =???',
        'do not kill me',
        'XP',
        'you',
        'Im bot',
        '???',
        ':)',
        ',.;:+-/*[´{()}´]',
        '´´',
        '+',
        '-',
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        'day 1',
        'New Assault',
        'New siege',
        'New siege',
        'im stupid',
        ' ',
        '2023 sorprendeme',
        'Notch',
        'Pumped Up Kicks',
        'PC',
        'Computer',
        'AI_',
        'á é í ó ú ü ç',
        '123456789',
        'Arena Closer',
        'hi',
        'Basic Tank Guy',
        'Feash',
        'Max XD',
        'ALIMENTAME',
        'SNIPPER',
        'I´m a cute girl',
        'm',
        'Overmancer YT',
        'Praca',
        ':D',
        '342',
        'Strong',
        '250 Names!',
        'Marckito',
        'ryuu',
        'hadlof itler',
        '',
        '',
        '',
        '',
        'temertly',
        'this is tale of',
        'Hate___love++++',
        '_',
        '-',
        '|',
        '[base]',
        '[fire]',
        '[water]',
        'Adolf[base]',
        'Hitler[fire]',
        'Naz1[water]',
        'germany[trap]',
        'odin[octo]',
        '[octo]',
        '[VN]infinity',
        'H.js',
        '[KPK]',
        '[KPK]penetrator',
        '[VN]',
        'Bean OStm',
        '[sword]...',
        '◘◘◘◘◘◘',
        'WHITE.404',
        '3 week no play',
        '[VPN]',
        'KILLER 💀',
        'skibidi toilet',
        'pet',
        'inifensive',
        '👽 Alien 👽',
        'Ukranie',
        'Ukranie peace',
        'titan camera',
        'titan speakerman',
        'titan Tv',
        'cameraman',
        'speakerman',
        'Tv-man',
        '',
        '',
        'pitos XD',
        '[',
        ']',
        '29/7/22',
        '29/8/22',
        '17/7/23',
        'helicopter speaker',
      //}
    ]);*/
    const names = [
        'Alpha',
        'boss',
        'November',
        'Victor',
        'X-Ray',
        'ñ',
        'im not a bot',
        'premium',
        '#Shorts',
        'новобранец',
        '11000011 10110001',
        'ü',
        'XD',
        'IP: 425.257.587',
        '',
        'ZzZ',
        'XD 2',
        'fuck you',
        'humans = trash',
        'UWU',
        '3rR0R',
        'dead furrys',
        'que pro',
        '([{¿¡a!?}])',
        'Laaaaaaag',
        '100% bot',
        'michi',
        'tank',
        'el Xokas',
        'que pro en 4k',
        'A',
        'fdhgfhjk',
        'MISSIGNO',
        'Minecraft',
        'free fire is good',
        'free fire is ZzZ',
        'Geometry dash',
        'Undefined',
        'an unnamed tank',
        'hexagon',
        'la roca XD',
        'Ñ + Ç =???',
        'do not kill me',
        'XP',
        'Que pendej*',
        '360 / 7 = 51.4285714286',
        'ehjeihjiehjhiehjheihej',
        'you',
        'Im bot',
        'spelling error',
        'MEXICANO',
        'á, é, í, ó, ú',
        'Bob',
        'Carmen',
        'David',
        'Janet',
        'Lorenzo',,
        'Roger',
        'Tommy 11',
        'Vincent',
        'Delta',
        'Lima',
        'November',
        'Uniform',
        'Zulu',
        'undefined',
        'VIVA LATAM',
        'paladise',
        'battleship',
        'Anhihilator',
        'Nailgun',
        'Mach gun',
        'NACHOS',
        'your ZzZ',
        'CSM',
        'Peru',
        'Argentina',
        'United States',
        'ahhhhh',
        'other name more',
        'Canada',
        'USA',
        'No deberia existir XD',
        //'porque soy este equpo :(',
        '???',
        ':)',
        'Alejandro',
        'head',
        'beta tester',
        'good day',
        'bye',
        'LOVE = ilusion',
        'Happy new year',
        'Merry christmas',
        'dulce o mierda',
        'oh estoy bloqueado',
        ////(let * = 4;);
        '4Ml0 é G*Y',
        //'im Alklina',
        'let ñ = n+-',
        'glitch is ZzZ',
        'glitch is good',
        'the R',
        'earth',
        //'ladron',
        'palta',
        'aguacate',
        'MAS Ñ',
        //'bailar',
        ',.;:+-/*[´{()}´]',
        '´´',
        //'+',
        //'-',
        //'AWA',
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        'day 1',
        'New Assault',
        'im stupid',
        'ho',
        ' ',
        //'happy 4 july',
        'Jaunary',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'December',
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Monday',
        'Lunes',
        'Peggle',
        '2023 sorprendeme',
        'MAGIC! Rude',
        'Poker Face',
        'Aserejé',
        'Material Girl',
        'Notch',
        'David Medrano',
        'Pumped Up Kicks',
        'PC',
        'Computer',
        'AI_',
        'á é í ó ú ü ç',
        'Andre100proo XD',
        'Andre100pro XD',
        'Andre100',
        'Funado!',
        '123456789',
        'Foster the Pepole',
        'Wenomechainsama',
        'Tumajarbisaun',
        'Wifenlooof',
        'Eselifterbraun',
        'Arena Closer',
        'Sin Importar',
        'hi',
        'Tank',
        'Basic Tank Guy',
        'Feash',
        'Max XD',
        'ALIMENTAME',
        'SNIPPER',
        'I´m a cute girl',
        'm',
        'Moves Like Jagger',
        'New Rules',
        'Overmancer YT',
        'Praca',
        'Jymmi',
        'Jimmy',
        ':D',
        '342',
        'Strong',
        'Woomy arras.io',
        'The woorm house',
        '3!',
        '2!',
        '1!',
        '250 Names!',
        'Marckito',
        'ryuu',
        'hadlof itler',
        '',
        '',
        '',
        '',
        'temertly',
        'this is tale of',
        'Hate___love++++',
        '_',
        '-',
        '|',
        '[base]',
        '[fire]',
        '[water]',
        'Adolf[base]',
        'Hitler[fire]',
        'Naz1[water]',
        'germany[trap]',
        'odin[octo]',
        '[octo]',
        '[VN]infinity',
        'H.js',
        '[KPK]',
        '[KPK]penetrator',
        '[VN]',
        'Bean OStm',
        '[sword]...',
        '²■☺',
        '☺☻♥♦♣♠•◘○',
        '◘◘◘◘◘◘',
        'WHITE.404',
        '3 week no play',
        '[VPN]',
        '[VPN]69 89',
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'n',
        'o',
        'p',
        'q',
        'r',
        's',
        't',
        'u',
        'v',
        'w',
        'x',
        'y',
        'z',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'KILLER 💀',
        'skibidi toilet',
        'Thiepkiel',
        'Nytrxi',
        'pet',
        'inifensive',
        '👽 Alien 👽',
        'XxX pedrito XxX',
        'π',
        'π = 3,14159265358979323846264338327950288419716939',
        'Ukranie',
        'Ukranie peace',
        'titan camera',
        'titan speakerman',
        'titan Tv',
        'cameraman',
        'speakerman',
        'Tv-man',
      //{
        'Alpha',
        'boss',
        'November',
        'Victor',
        'X-Ray',
        'ñ',
        'im not a bot',
        'premium',
        'новобранец',
        '11000011 10110001',
        'pink cheese green goes',
        'VIVA MÉXICO',
        'ü',
        'XD',
        'IP: 425.257.587',
        '',
        'que noob',
        'andre100noob DX',
        'ZzZ',
        'fuck you',
        '3rR0R',
        '([{¿¡a!?}])',
        'Laaaaaaag',
        '100% bot',
        'michi',
        'tank',
        'A',
        'fdhgfhjk',
        'Undefined',
        'an unnamed tank',
        'hexagon',
        'Ñ + Ç =???',
        'do not kill me',
        'XP',
        'you',
        'Im bot',
        '???',
        ':)',
        ',.;:+-/*[´{()}´]',
        '´´',
        '+',
        '-',
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        'day 1',
        'New Assault',
        'New siege',
        'New siege',
        'im stupid',
        ' ',
        '2023 sorprendeme',
        'Notch',
        'Pumped Up Kicks',
        'PC',
        'Computer',
        'AI_',
        'á é í ó ú ü ç',
        '123456789',
        'Arena Closer',
        'hi',
        'Basic Tank Guy',
        'Feash',
        'Max XD',
        'ALIMENTAME',
        'SNIPPER',
        'I´m a cute girl',
        'm',
        'Overmancer YT',
        'Praca',
        ':D',
        '342',
        'Strong',
        '250 Names!',
        'Marckito',
        'ryuu',
        'hadlof itler',
        '',
        '',
        '',
        '',
        'temertly',
        'this is tale of',
        'Hate___love++++',
        '_',
        '-',
        '|',
        '[base]',
        '[fire]',
        '[water]',
        'Adolf[base]',
        'Hitler[fire]',
        'Naz1[water]',
        'germany[trap]',
        'odin[octo]',
        '[octo]',
        '[VN]infinity',
        'H.js',
        '[KPK]',
        '[KPK]penetrator',
        '[VN]',
        'Bean OStm',
        '[sword]...',
        '◘◘◘◘◘◘',
        'WHITE.404',
        '3 week no play',
        '[VPN]',
        'KILLER 💀',
        'skibidi toilet',
        'pet',
        'inifensive',
        '👽 Alien 👽',
        'Ukranie',
        'Ukranie peace',
        'titan camera',
        'titan speakerman',
        'titan Tv',
        'cameraman',
        'speakerman',
        'Tv-man',
        '/*',
        '*/',
        'pitos XD',
        '[',
        ']',
        '29/7/22',
        '29/8/22',
        '17/7/23',
        'helicopter speaker',
        /*'merry christmas!!!',
        '¡¡¡feliz navidad!!!',
        'С Рождеством!!!',
        'Joyeux Noël!!!',
        'feliz Natal!!!',
        'Buon Natale!!!',
        'Frohe Weihnachten!!!',*/
        'Enamorado tuyo',
      
        'Hermana',
        'De',
        'Melody',
        'Ojalá',
        'me',
        'onocieras',
        'pero',
        'tu',
        'ya',
        'tienes',
        'tu',
        'propio',
        'amor',
        'asi',
        'que',
        'ya',
        'no',
        'importaria',
        'en',
        'tu',
        'vida',
        'Y si te parece si yo',
        'Estoy enamorado tuyo',
        'ART Proyect',
        '24/10/23',
        '!! BRILLANT !!',
        'Teory',
        'Elite destructor',
        'I hate maths',
        'Alan becker',
        'a',
        'alt+f4',
        'Kill me',
        'servidor en decadencia',
        'server on decadency',
        'Fear',
        'bite me',
        'uzi',
        'n',
        'v',
        'j',
        'cyn',
        'darkxwolf17',
        'st',
        'max',
        'augustus',
        'yosseline',
        'isaac',
        'alan',
        'capi',
        'axel',
        'alex',
        'el santi',
        'santi vende dulces',
        'el borolas',
        'el burras',
        'goo',
        'gooey goo',
        'toxic goo',
        'kyle gabler',
        'alfonso',
        'melody',
        'vicente',
        'isaac',
        'antimonio',
        'hidrogeno',
        'fluor',
        'agusimp',
        'roberto',
        'omar es una mierda',
        'oahit',
        'UnNombreGenerico',
        'texto rojo',
        'digital love',
        'killeable basic',
        'emily',
        'jazmin',
        'ch0ko_milk',
        'skarlet',
        'Jalisco',
        'sheimbaun',
        'Trump',
        'eres putin',
        'solo por asi acaso',
        'gooballer56lol100',
        'int nobody',
        'i',
        'never',
        'talked',
        'with',
        'she',
        'touch',
        'katerine',
        'sr estimado fino',
      //}
    ];
    return names[Math.floor(Math.random() * names.length)];
};

exports.chooseBossName = (code, n) => {
    switch (code) {
    case 'a':
    return exports.chooseN([
        'Archimedes',
        'Akilina',
        'Anastasios',
        'Athena',
        'Alkaios',
        'Amyntas',
        'Aniketos',
        'Artemis',
        'Anaxagoras',
        'Apollon',
        'Aphrodite',
    ], n);
    case 'castle':
    return exports.chooseN([
        'Berezhany',
        'Lutsk',
        'Dobromyl',
        'Akkerman',
        'Palanok',
        'Zolochiv',
        'Palanok',
        'Mangup',
        'Olseko',
        'Brody',
        'Isiaslav',
        'Kaffa',
        'Bilhorod',
    ], n);
    case 'Bosses':
    return exports.chooseN([
        'Hermes',
        'Dionisio',
        'Zeus',
        'Poseidon',
        'Demeter',
        'Hephaestus',
        'Hera',
        'Thor',
        'Loki',
        'Frigg',
        'Balder',
    ], n);
    case 'sanctuaryFood':
    return exports.chooseN([
        'golden',
        'silver',
        'bronze',
        'diamond',
        'neon',
        'argon',
        'mercury',
        'carbon',
        'iron',
        'methane',
        'hydrogen',
        'cobalt',
    ], n);
    case 'nothing':
    return exports.chooseN([
        ' ',
    ], n);
    case 'tyr':
    return exports.chooseN([
        'Tyr',
        'Tyr',
    ], n);
    case 'fiolnir':
    return exports.chooseN([
        'Fiolnir',
        'Fiolnir',
    ], n);
    case 'alviss':
    return exports.chooseN([
        'Alviss',
        'Alviss',
    ], n);
    case 'thrud':
    return exports.chooseN([
        'Thrud',
        'Thrud',
    ], n);
    case 'theia':
    return exports.chooseN([
        'Theia',
        'Theia',
    ], n);
    case 'zaphkiel':
    return exports.chooseN([
        'Zaphkiel',
        'Zaphkiel',
    ], n);
    case 'nyx':
    return exports.chooseN([
        'Nyx',
        'Nyx',
    ], n);
    case 'paladin':
    return exports.chooseN([
        'Paladin',
        'Paladin',
    ], n);
    case 'freyja':
    return exports.chooseN([
        'Freyja',
        'Freyja',
    ], n);
    //case 'king of chaos':
    case 'supreme':
    return exports.chooseN([
        'Anubis',
        'Jupiter',
        'Huitzilopochtli',
        'Odín',
    ], n)
    case 'LegionaryCrasher':
    return exports.chooseN([
        'Vesta',
        'Juno',
        'Ocru',
        'Jano',
        'Minerva',
        'Ceres',
    ], n)
    case 'ragnarok':
    return exports.chooseN([
        'Ragnarok',
        'Ragnarok',
    ], n)
    case 'kronos':
    return exports.chooseN([
       'Kronos',
       'Kronos',
    ], n)
    case 'Ares':
    return exports.chooseN([
        'Ares',
        'Ares',
    ], n)
    case 'Gersemi':
    return exports.chooseN([
       'Gersemi',
       'Gersemi',
    ], n)
    case 'Ezekiel':
    return exports.chooseN([
        'Ezekiel',
        'Ezekiel',
    ], n)
    case 'Eris':
    return exports.chooseN([
       'Eris',
       'Eris',
    ], n)
    case 'Selene':
    return exports.chooseN([
       'Selene',
       'Selene',
    ], n)
    case 'ArenaCloser':
    return exports.chooseN([
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
       'Arena Closer',
    ], n)
    default: return 'God';
    }
};
  
}
